[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "checkmate3"
version = "0.2.0"
description = "A meta-code checker written in Python."
readme = "README.md"
license = "AGPL-3.0"
authors = ["adewes", "marcinguy"]

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: AGPL-3.0",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Topic :: Software Development :: Quality Assurance"
]

dependencies = [
  "blitzdb3_ce==1.0.0",
  "pylint",
  "pyflakes",
  "pep8",
  "chardet",
  "pyyaml",
  "sqlalchemy"
]

[tool.poetry.urls]
homepage = "https://github.com/tcosolutions/checkmate-ce"
